In [32]:
import numpy as np

In [47]:
# This is a null vector i.e. (zeros)

z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
# vector of elements from 10 to 49

a = np.arange(10,50,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [60]:
a.shape

(40,)

In [61]:
a.dtype

dtype('int32')

In [97]:
# numpy version

np.version

<module 'numpy.version' from 'c:\\python\\python37\\lib\\site-packages\\numpy\\version.py'>

In [98]:
# numpy configuration

np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [62]:
a.ndim

1

In [75]:
# boolean array of true values

b = np.array([1,1,1,1,1], dtype='bool')
print(b)

[ True  True  True  True  True]


In [78]:
# 2 dim array

d = np.array([[1, 2], [3, 4]])
d

array([[1, 2],
       [3, 4]])

In [84]:
# 3 dim array

r = np.array([[[1, 2, 3], [2, 3, 6]], [[3, 4, 5], [1, 2 ,3]]])
r

array([[[1, 2, 3],
        [2, 3, 6]],

       [[3, 4, 5],
        [1, 2, 3]]])

In [ ]:
# NOW THE DIFFICULTY LEVEL: EASY

In [100]:
# Reverse a vector

c = np.array([1, 2, 3, 4, 5])
c[::-1]

array([5, 4, 3, 2, 1])

In [112]:
# making fifth element '1'

n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [102]:
# 3x3 Identity matrix

i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
# Float data type

arr = np.array([1, 2, 3, 4, 5], dtype = 'float64')
arr

array([1., 2., 3., 4., 5.])

In [123]:
# multiplication of arrays

arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [188]:
# NOW THE DIFFICULTY LEVEL: MEDIUM

In [140]:
# Replacing the element 5 by 12

arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [145]:
# Replacing the first vector by [64, 64, 64]

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 0] = [64, 64, 64]
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
# Slicing out first element from first 1D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = arr[0,0]
a

1

In [151]:
# Slicing out second element from second 1D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr[1,1]
b

5

In [154]:
# Slicing out 3rd column from only first 2 rows

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[0:2, 2]

array([3, 6])

In [173]:
# 10x10 array of random values and find min and max values

arr = np.random.rand(10,10)
np.min(arr)
np.max(arr)

0.9948387884226758

In [179]:
# Find the common elements of the 2 arrays

a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [180]:
# Return the position where the elements match

a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b, return_indices = True)

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

In [187]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
np.intersect1d(names,data, return_indices='Will')

(array([], dtype='<U32'), array([], dtype=int64), array([], dtype=int64))

In [ ]:
# NOW THE DIFFICULTY LEVEL: DIFFICULT

In [206]:
# 2D array of random numbers between 1 & 15

a = np.random.randint(1,15, (3, 2))
a

array([[ 7,  6],
       [14,  9],
       [ 7,  5]])

In [207]:
# Array of shape (2, 2, 4) of random numbers between 1 & 16

a = np.random.randint(1,16, (2, 2, 4))
a

array([[[14, 15,  5,  4],
        [ 4,  6, 15,  6]],

       [[ 8, 10, 14,  8],
        [ 6,  2, 11, 10]]])

In [217]:
# Swapping axes

a = np.random.randint(1,15, (3, 2))
np.swapaxes(a,0,1)

array([[ 4,  3,  5],
       [ 2, 10, 12]])

In [228]:
# Square-root

a = np.random.randint(1,10, (1,10))
b = a**1/2
b

array([[3. , 2.5, 1.5, 4.5, 2. , 0.5, 4. , 3.5, 2.5, 3.5]])